### ISSUE TITLE
Building Data Lake- S3 Bucket creation error in us-east-1

### ISSUE THREAD

**Issue by rmalecky** [aws-samples/aws-research-workshops#1]
aws-research-workshops/notebooks/building_data_lakes/building_data_lakes.ipynb

`session.resource('s3').create_bucket(Bucket=bucket, CreateBucketConfiguration={'LocationConstraint': region})`
throw an error in us-east-1.  Removing the constraint seems to address  the issue.  It looks like us-east-1 isn't a valid input for LocationConstraint

**Comment by randyridgley** [comment]
Made changes to the workshop code to work for both us-east-1 and the other commercial regions
