### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by aravind-craft** [aws-samples/aws-research-workshops#2]
**Describe the bug**
Access denied https://s3.amazonaws.com/big-data-workshop-us-east-1/research-env.yml

**To Reproduce**
1. Go to https://github.com/aws-samples/aws-research-workshops
2. Click on Launch Stack
3. In AWS Console (Cloudformation), click Next
4. You get error

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Comment by bitshop** [comment]
This is still an issue, sigh.

**Comment by jxuamazon** [comment]
please download the research-env.yml (in the root fold of this repo) to your local file system and use that file as the CloudFormation template
